name: Post Release to Discord

on:
  release:
    types:
      - published

jobs:
  post-release-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Post Release on Discord
        uses: SethCohen/github-releases-to-discord@v1.15.0
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          username: "Release Changelog"
          avatar_url: "https://cdn.discordapp.com/icons/751317910504603701/ec26ab4881753077e06122da7b78bf7c.webp"
          max_description: 2000
