name: Updates Docs

on:
  repository_dispatch:
    types: [docs]
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
      - name: Extract commands web file
        run: |
          7z x ./docs/commands/commands.7z -o./docs/commands
          rm ./docs/commands/commands.7z
      - name: Deploy commands file
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs/commands
          clean: false
          force: false
